---
title: "Interpretation of Results"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Interpretation of Results}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Target Market Share

The `target_market_share()` function calculates the Target Market Share metric and outputs a table including the calculated targets at the portfolio level or at the company level, depending on the options selected.

### Explanation of Output

[2 or 3 sentences explaining how to read the output]

For detailed information about the table output of the `target_market_share()` function and its columns, see the [data dictionary](data_outputs.html#target_market_share-output).

For detailed information about the Target Market Share metric and how it is calculated, see the [Metrics appendix](cookbook_metrics.html#market-share-approach).

### Interpretation & Intuition

[2 or 3 sentences about interpretation]

[2 or 3 sentences about intuition]

## Sectoral Decarbonization (SDA) Target

The `target_sda()` function calculates the Sectoral Decarbonization Target metric and outputs a table including the calculated targets at the portfolio level or at the company level, depending on the options selected.

### Explanation of Output

[2 or 3 sentences explaining how to read the output]

For detailed information about the table output of the `target_market_share()` function and its columns, see the [data dictionary](data_outputs.html#target_sda-output).

For detailed information about the Target Market Share metric and how it is calculated, see the [Metrics appendix](cookbook_metrics.html#sectoral-decarbonization-approach).

### Interpretation & Intuition

[2 or 3 sentences about interpretation]

[2 or 3 sentences about intuition]

**PREVIOUS CHAPTER:** [Running the Analysis](cookbook_running_the_analysis.html)

**NEXT CHAPTER:** [Advanced Use Cases](cookbook_advanced_use_cases.html)
