---
title: "Loanbook"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Loanbook}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, echo = FALSE}
plot_table <- function(dataset_name) {
  library(r2dii.data)
  table <- r2dii.data::data_dictionary
  table <- dplyr::filter(table, .data[["dataset"]] == dataset_name)
  table <- dplyr::arrange(table, match(column, names(get(dataset_name))))
  table_plot <- gt::gt(dplyr::select(table, -"dataset"))
  
  table_plot <- 
    gt::cols_width(
      .data = table_plot,
      column ~ gt::px(150),
      typeof ~ gt::px(90)
    )
  
  table_plot <-
    gt::tab_style(
      data = table_plot,
      style = gt::cell_text(size = "smaller"),
      locations = gt::cells_body(columns = 1:2)
    )
  
  table_plot <-
    gt::tab_options(
      data = table_plot,
      ihtml.active = TRUE,
      ihtml.use_pagination = FALSE,
      ihtml.use_sorting = TRUE,
      ihtml.use_highlight = TRUE
    )
  
  gt::fmt_passthrough(table_plot)
}
```

## Loanbook dataset

Loanbook dataset, prepared for the software PACTA (Paris Agreement Capital Transition Assessment).

```{r, echo = FALSE}
plot_table("loanbook_demo")
```

The `{r2dii.data}` package provides an example loanbook dataset `r2dii.data::loanbook_demo`.

```{r, R.options = list(width = 400)}
r2dii.data::loanbook_demo
```
